### ISSUE TITLE
I wasn't able to fix this two

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/accessibility-fixer-upper#2]
<img width="495" alt="image" src="https://user-images.githubusercontent.com/55094325/79286021-4d43d100-7e8d-11ea-8519-29e824b0cf7d.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/55094325/79286051-69e00900-7e8d-11ea-856f-7addcddad8ea.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/55094325/79286084-795f5200-7e8d-11ea-9860-95f03242d18f.png">

my font is wrong.
@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab 
1) So when using aria-details, you technically don't need to add anythign to your alt= tags. So you can remove all of your descriptions from the alt tags for this assignment.
2) I think for the a href issues, you currently have a text-decoration: none on them, but you should remove that because it's not accessible to not have an underline for links

Hope that helps!

**Comment by Samirahajiragab** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/55094325/79342746-80bd4480-7efb-11ea-96c9-e66dc50c8009.png">
thanks that helps but i still have fix this issues
 for the href   text-decoration: uderline
is it for a tag or nav or both ?
@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab 

Looks like you have your id="about" in the wrong spot.. you have both your shrubs id and about id kind of in the same place. All of you id's that your nav is pointing to should be on `<section>`s

Ah sorry, you might need to add in text-decoration: none back, an then add ing this:

.nav a:hover,
.nav a:focus {
  background-color: #fff;
  color: #113c00;
}
